version: '3'
services:
  webapp:
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        buildno: 1
 docker:
    -Ddocker.projectKey: "api1"
    -Ddocker.projectName: "api2"
    -Dappname: "api3"
    -Ddocker.sources: "api4"
   
   
