version: '3'
services:
  webapp:
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        buildno: 1
docker:
      docker.projectKey: "api1"
      docker.projectName: "api2"
      appname: "api3"
      docker.sources: "api4"
   
   
